// REDUX ACTION TYPES
export const TICK = "TICK"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const RESET = "RESET"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const SET_MESSAGE = "SET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const IS_LOADING_DOCTORS_BY_PAGE = "IS_LOADING_DOCTORS_BY_PAGE"
export const FETCH_DOCTORS_BY_PAGE = "FETCH_DOCTORS_BY_PAGE"

// Categories
export const IS_LOADING_CATEGORIES_BY_PAGE = "IS_LOADING_CATEGORIES_BY_PAGE"
export const FETCH_CATEGORIES_BY_PAGE = "FETCH_CATEGORIES_BY_PAGE"

// Articles
export const IS_LOADING_ARTICLES_BY_PAGE = "IS_LOADING_ARTICLES_BY_PAGE"
export const FETCH_ARTICLES_BY_PAGE = "FETCH_ARTICLES_BY_PAGE"

// Quizzes
export const IS_LOADING_QUIZZES_BY_PAGE = "IS_LOADING_QUIZZES_BY_PAGE"
export const FETCH_QUIZZES_BY_PAGE = "FETCH_QUIZZES_BY_PAGE"

export const ADD_CART_ITEMS = "ADD_CART_ITEMS"
// export const FETCH_DOCTORS_BY_PAGE = "FETCH_DOCTORS_BY_PAGE";
